repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.8
    hooks:
      - id: clang-format
        args: [--style=file:.vscode/format/.clang-format]
        types_or: [c++]
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
        args: [--line-length=130]
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [--config=.vscode/lint/ament_flake8.ini]
        additional_dependencies:
          - flake8-quotes
          - flake8-docstrings
          - flake8-import-order
