#!/bin/bash

if [[ -f ".env" ]]; then
    source ".env"
fi

if [[ -z "${VSCODE_DEVCONTAINER_IMAGE:-}" ]]; then
    # assemble default image name generated by docker-ros based on git remote and branch
    container_registry="ghcr.io"
    if git remote | grep -q "^origin$"; then
        git_remote="$(git remote get-url origin)"
        if [[ "${git_remote}" == git@* ]]; then
            repo_path="$(printf '%s' "${git_remote}" | cut -d':' -f2 | rev | cut -d'.' -f2- | rev | tr '[:upper:]' '[:lower:]')"
        else
            repo_path="$(printf '%s' "${git_remote}" | sed -e 's/https:\/\/[^/]*\///' -e 's/\.git\/\?$//' | tr '[:upper:]' '[:lower:]')"
        fi
        image_tag="latest-dev"
        git_branch_slug="$(git branch --show-current | iconv -t ascii//TRANSLIT | sed -r 's/[^a-zA-Z0-9]+/-/g' | sed -r 's/^-+\|-+$//g' | tr 'A-Z' 'a-z')"
        if [[ "${git_branch_slug}" != "main" ]]; then
            image_tag="latest-dev_${git_branch_slug}_ci"
        fi
    fi
    image="${container_registry}/${repo_path}:${image_tag}"
else
    # overwrite image name from .env, if existent
    image="${VSCODE_DEVCONTAINER_IMAGE}"
fi
echo "Dev Container Image: '${image}'"

# build locally if explicitly requested, or when image is unavailable locally/remotely
if [[ -n "${VSCODE_DEVCONTAINER_LOCAL_BUILD:-}" ]] || {
    ! docker pull "${image}" && ! docker image inspect "${image}" &>/dev/null
}; then
    if [[ -n "${VSCODE_DEVCONTAINER_LOCAL_BUILD:-}" ]]; then
        echo "VSCODE_DEVCONTAINER_LOCAL_BUILD is set, building Dev Container image locally with docker-ros"
    else
        echo "Dev Container Image '${image}' not found locally or remotely, building locally with docker-ros"
    fi
    IMAGE="${image}" ./docker/docker-ros/scripts/build.sh
fi

# create local Dockerfile copy with default build arguments to set image/uid/gid
cp ".devcontainer/Dockerfile" ".devcontainer/Dockerfile.local"
sed -i "s~ARG IMAGE~ARG IMAGE=${image}~g" .devcontainer/Dockerfile.local
sed -i "s~ARG DOCKER_UID~ARG DOCKER_UID=$(id -u)~g" .devcontainer/Dockerfile.local
sed -i "s~ARG DOCKER_GID~ARG DOCKER_GID=$(id -g)~g" .devcontainer/Dockerfile.local

# ensure optional local mounts exist
mkdir -p "${HOME}/.claude"
mkdir -p "${HOME}/.codex"
