#!/bin/bash

if [[ -f ".env" ]]; then
    source ".env"
fi

# helper function to build image locally with docker-ros
build_with_docker_ros() {

    local docker_dir="docker"
    local docker_ros_dir="${docker_dir}/docker-ros"
    local docker_ros_url="https://github.com/ika-rwth-aachen/docker-ros.git"
    local docker_ros_ref="${VSCODE_DEVCONTAINER_DOCKER_ROS_REF:-main}"
    local docker_ros_created=false
    local build_exit_code=0

    # clone docker-ros on-demand if not already available
    if [[ ! -d "${docker_ros_dir}" ]]; then
        mkdir -p "${docker_dir}"
        echo "docker-ros not found at '${docker_ros_dir}', cloning '${docker_ros_url}' (ref '${docker_ros_ref}') on-demand"
        if ! git clone --depth 1 "${docker_ros_url}" "${docker_ros_dir}"; then
            echo "Failed to clone docker-ros from '${docker_ros_url}'" >&2
            return 1
        fi
        if ! git -C "${docker_ros_dir}" fetch --depth 1 origin "${docker_ros_ref}" || ! git -C "${docker_ros_dir}" checkout -q FETCH_HEAD; then
            echo "Failed to check out docker-ros ref '${docker_ros_ref}'" >&2
            rm -rf "${docker_ros_dir}"
            return 1
        fi
        docker_ros_created=true
    fi

    # build image locally with docker-ros
    IMAGE="${image}" "${docker_ros_dir}/scripts/build.sh"
    build_exit_code=$?

    # cleanup on-demand docker-ros clone after build, if it was created by this script
    if [[ "${docker_ros_created}" == "true" ]]; then
        echo "Removing on-demand docker-ros checkout at '${docker_ros_dir}'"
        rm -rf "${docker_ros_dir}"
    fi

    return "${build_exit_code}"
}

if [[ -z "${VSCODE_DEVCONTAINER_IMAGE:-}" ]]; then
    # assemble default image name generated by docker-ros based on git remote and branch
    container_registry="ghcr.io"
    if git remote | grep -q "^origin$"; then
        git_remote="$(git remote get-url origin)"
        if [[ "${git_remote}" == git@* ]]; then
            repo_path="$(printf '%s' "${git_remote}" | cut -d':' -f2 | rev | cut -d'.' -f2- | rev | tr '[:upper:]' '[:lower:]')"
        else
            repo_path="$(printf '%s' "${git_remote}" | sed -e 's/https:\/\/[^/]*\///' -e 's/\.git\/\?$//' | tr '[:upper:]' '[:lower:]')"
        fi
        image_tag="latest-dev"
        git_branch_slug="$(git branch --show-current | iconv -t ascii//TRANSLIT | sed -r 's/[^a-zA-Z0-9]+/-/g' | sed -r 's/^-+\|-+$//g' | tr 'A-Z' 'a-z')"
        if [[ "${git_branch_slug}" != "main" ]]; then
            image_tag="latest-dev_${git_branch_slug}_ci"
        fi
    fi
    image="${container_registry}/${repo_path}:${image_tag}"
else
    # overwrite image name from .env, if existent
    image="${VSCODE_DEVCONTAINER_IMAGE}"
fi
echo "Dev Container Image: '${image}'"

# build locally if explicitly requested, or when image is unavailable locally/remotely
if [[ -n "${VSCODE_DEVCONTAINER_BUILD_LOCALLY:-}" ]] || {
    ! docker pull "${image}" && ! docker image inspect "${image}" &>/dev/null
}; then
    if [[ -n "${VSCODE_DEVCONTAINER_BUILD_LOCALLY:-}" ]]; then
        echo "VSCODE_DEVCONTAINER_BUILD_LOCALLY is set, building Dev Container image locally with docker-ros"
    else
        echo "Dev Container Image '${image}' not found locally or remotely, building locally with docker-ros"
    fi
    build_with_docker_ros
fi

# create local Dockerfile copy with default build arguments to set image/uid/gid
cp ".devcontainer/Dockerfile" ".devcontainer/Dockerfile.local"
sed -i "s~ARG IMAGE~ARG IMAGE=${image}~g" .devcontainer/Dockerfile.local
sed -i "s~ARG DOCKER_UID~ARG DOCKER_UID=$(id -u)~g" .devcontainer/Dockerfile.local
sed -i "s~ARG DOCKER_GID~ARG DOCKER_GID=$(id -g)~g" .devcontainer/Dockerfile.local

# ensure optional local mounts exist
mkdir -p "${HOME}/.claude"
mkdir -p "${HOME}/.codex"
