name: compose

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  workflow_dispatch:

jobs:
  compose:
    uses: openads-project/openads-dev-environment/.github/workflows/compose.yml@main
    secrets: inherit
