name: helm

on: # TODO
  push:
    branches:
      - '**'
    tags:
      - '**'
  workflow_dispatch:

jobs:
  helm:
    uses: openads-project/openads-dev-environment/.github/workflows/helm.yml@main
    secrets: inherit
