name: consistency

on:
  workflow_call:

jobs:
  consistency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install script dependencies
        run: python3 -m pip install -r .dev-environment/scripts/requirements.txt
      - name: Run consistency checks
        run: python3 .dev-environment/scripts/check_repository_consistency.py
