name: generators

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  generators:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout openads-dev-environment
        uses: actions/checkout@v4

      - name: Install dependencies via pip
        run: python3 -m pip install -r scripts/requirements.txt

      - name: Run generator pytests
        run: python3 -m pytest tests/test_generate_compose.py tests/test_generate_readme.py
